'use client';
import {ChevronLeft,ChevronRight,ArrowUpRight} from 'lucide-react';
const stages=[
 {title:'Hardpoint thật trên chassis',parts:'chassis beam hiện hữu · 32524 · 2780',body:'Bộ giải tự tìm hai beam dọc thuộc group chassis, biến đổi chính tâm các lỗ Technic từ matrix gốc của model rồi chọn bốn hardpoint đối xứng. Vòng xanh đánh dấu đúng tâm lỗ được chọn. Beam 7L của giá đỡ nằm lệch đúng một lớp Technic và pin cắm qua các hardpoint này; không còn đặt cả khung bằng tọa độ đoán.'},
 {title:'Hai side-truss tam giác thấp',parts:'32524 · 6558 · 6536',body:'Mỗi bên dùng một đáy 7L và hai diagonal 7L tạo tam giác thấp. Hai diagonal nằm ở hai lớp kế nhau và khóa bằng pin 3L nên không chồng mesh. Cross block 6536 ở đỉnh đổi hướng liên kết từ mặt phẳng truss sang bridge phía trên.'},
 {title:'Cross-camera bridge',parts:'32316 · 32524/40490/32525/41239/32278 · 2780 · 6558',body:'Hai rail 5L chạy dọc nối hai đỉnh truss. Chiều dài beam ngang được chọn tự động từ khoảng cách thật giữa hai side-truss: chỉ nhận 7L, 9L, 11L, 13L hoặc 15L khi tâm lỗ khớp; không scale beam để ép vừa.'},
 {title:'Cradle 19 stud + side stop',parts:'32278 · 32316 · 6536 · 2780',body:'Mỗi ledge dùng beam 15L ở giữa và beam 5L hai đầu chồng ba lỗ ở lớp kế bên, tạo bề rộng thực gần 19 stud cho Aris. Hai stop thấp ở mép chống trượt nhưng không dựng khung quanh góc camera. Dây elastic ở bước cuối là phụ kiện thật, được render khác vật liệu LEGO.'},
 {title:'Aris + camera clearance',parts:'Vsmart Aris GLB · elastic strap',body:'Điện thoại dùng trực tiếp model GLB đã cung cấp, đặt landscape và nghiêng khoảng 10° xuống mặt đường. Camera sau hướng về đầu xe. Aid FOV chỉ dùng để kiểm tra clearance; Drive mode ẩn toàn bộ aid và giữ khung khóa theo hardpoint chassis.'}
];
type Props={step:number;onStep:(n:number)=>void;context:boolean;onContext:(v:boolean)=>void;exploded:boolean;onExploded:(v:boolean)=>void};
export default function AdvancedPanel({step,onStep,context,onContext,exploded,onExploded}:Props){return <>
 <div className="advanced-title"><span className="small-label">CAMERA RIG / 02</span><h1>Low camera bridge.</h1><p>Chassis-resolved · stock LDraw · Vsmart Aris GLB</p></div>
 <div className="advanced-view-options"><button aria-pressed={!context} onClick={()=>onContext(false)}>Giá đỡ</button><button aria-pressed={context} onClick={()=>onContext(true)}>Vị trí trên xe</button><button aria-pressed={exploded} onClick={()=>onExploded(!exploded)}>Tách lớp</button></div>
 <aside className="advanced-panel" aria-label="Thiết kế giá đỡ điện thoại">
  <div className="advanced-meta"><span>DUAL SIDE-TRUSS</span><span>0{step+1} / 05</span></div>
  <h2>{stages[step].title}</h2><p className="mount-parts">{stages[step].parts}</p><p>{stages[step].body}</p>
  <nav className="mount-stages" aria-label="Các bước lắp giá đỡ">{stages.map((s,i)=><button key={s.title} aria-current={i===step?'step':undefined} onClick={()=>onStep(i)}><span>0{i+1}</span>{s.title}</button>)}</nav>
  <div className="mount-nav"><button disabled={step===0} onClick={()=>onStep(step-1)} aria-label="Bước giá đỡ trước"><ChevronLeft size={17}/></button><span>{step===4?'Kiểm tra camera':'Lắp theo đường truyền tải'}</span><button disabled={step===4} onClick={()=>onStep(step+1)} aria-label="Bước giá đỡ tiếp"><ChevronRight size={17}/></button></div>
  <details><summary>Cơ sở hình học</summary><dl><div><dt>Aris GLB</dt><dd>156,55 × 76,18 × 10,71 mm</dd></div><div><dt>Khoảng hardpoint dọc</dt><dd>6 stud · khớp beam 7L</dd></div><div><dt>Cradle</dt><dd>~19 stud · không kéo giãn beam</dd></div><div><dt>Phone tilt</dt><dd>10° xuống · cần calibrate FOV thật</dd></div></dl><p>Hardpoint được suy ra lúc runtime từ chính matrix của các straight Technic beam thuộc chassis. Bộ giải chỉ chấp nhận cặp rail có trục dọc xe, hướng lỗ phù hợp và cross-span khớp một beam stock. Nếu model chassis thay đổi mà không tìm được cặp hợp lệ, không được thay bằng tọa độ giả.</p><p>Asset dùng: 7L 32524, 5L 32316, cross block 6536, 15L 32278, pin 2780/6558 và một cross beam có chiều dài phù hợp. <a href="/ldraw-part-credits.txt" target="_blank" rel="noreferrer">Nguồn asset & tác giả ↗</a></p></details>
  <details><summary>Kiểm tra trước khi chạy</summary><p>Render khớp với chassis của LDraw 42096 hiện tại, nhưng xe thật đã độ motor vẫn phải kiểm tra clearance. Xác nhận pin vào đúng lỗ, beam không cạ steering/suspension, strap không che camera và điện thoại không chạm body panel khi hệ treo nén hết hành trình.</p></details>
  <details><summary>Lộ trình VLA</summary><p>Điện thoại thu hình; máy tính chạy perception/policy và gửi lệnh qua bộ giám sát. Chỉ bắt đầu thu dataset sau khi camera pose và độ rung của rig đã cố định.</p><a className="roadmap-link" href="/VLA-roadmap.md" target="_blank" rel="noreferrer">Đọc kế hoạch dữ liệu, training & triển khai <ArrowUpRight size={16}/></a></details>
 </aside>
 <div className="advanced-footnote">4 hardpoint từ chassis thật · dual side-truss · không scale LEGO · strap là phụ kiện riêng</div>
 </>}
