'use client';
import {mountInventory} from './phone-mount-parts';
import {ChevronLeft,ChevronRight,ArrowUpRight} from 'lucide-react';
const stages=[
 {title:'Điểm neo vào chassis',parts:'41239 · 32526 · 2780',body:'Viewer lấy trục dọc/ngang và mặt kết cấu trực tiếp từ các beam, liftarm và frame thuộc nhóm chassis của mô hình 42096. Hai rail 13L được đặt lên mặt kết cấu đó; beam chữ L 3 × 5 và pin 2L tạo chân nối xuống chassis thay vì tì lên panel thân xe. Vị trí lỗ/pin cuối cùng vẫn phải đối chiếu trên chiếc xe đã độ motor trước khi lắp thật.'},
 {title:'Tháp đỡ có giằng chéo',parts:'40490 · 32525 · 2780 · 6558',body:'Dựng bốn chân từ hai rail neo lên khay, rồi khóa bằng hai mặt phẳng giằng tam giác ở trước và sau. Tải từ điện thoại đi theo khay → tháp → rail → chassis; không truyền lực qua kính, cửa hay panel mui. Hai lớp giằng giúp giảm lắc ngang và lắc dọc khi xe tăng tốc hoặc rẽ.'},
 {title:'Khay đỡ bằng beam thật',parts:'41239 · 32524 · 18654 · 2780 · 6558',body:'Ghép hai beam 13L lệch một lớp, chồng 3 lỗ để tạo nhịp 23 stud. Hai beam 7L đỡ đáy máy. Spacer 1L và pin 2L/3L đều dùng đúng asset có sẵn. Đệm bảo vệ máy là phụ kiện ngoài LEGO, không được giả lập thành mảnh LEGO.'},
 {title:'Chặn cạnh và khóa trên',parts:'41239 · 32140 · 2780',body:'Dùng beam 13L làm trụ cạnh, beam chữ L 2 × 4 làm chặn góc và pin 2L để ghép. Không kéo giãn mảnh để vừa máy. Căn lại khe hở bằng vị trí lỗ và đệm bảo vệ riêng; kiểm tra không ép nút cạnh hoặc che camera.'},
 {title:'Lắp Aris, căn đường nhìn',parts:'Vsmart Aris thường · camera sau hướng đầu xe',body:'Đặt máy ngang, màn hình quay về đuôi xe; camera sau quay đúng theo trục trước của xe mà viewer vừa suy ra từ cụm front/rear. Chọn camera sau chính 1× và khóa chiều xoay video. Nón nhìn trong 3D chỉ minh họa hướng, chưa phải FOV đo.'}
];
type Props={step:number;onStep:(n:number)=>void;context:boolean;onContext:(v:boolean)=>void;exploded:boolean;onExploded:(v:boolean)=>void};
export default function AdvancedPanel({step,onStep,context,onContext,exploded,onExploded}:Props){return <>
 <div className="advanced-title"><span className="small-label">CAMERA RIG / 01</span><h1>Aris on board.</h1><p>LDraw / Linh kiện LEGO có sẵn</p></div>
 <div className="advanced-view-options"><button aria-pressed={!context} onClick={()=>onContext(false)}>Giá đỡ</button><button aria-pressed={context} onClick={()=>onContext(true)}>Vị trí trên xe</button><button aria-pressed={exploded} onClick={()=>onExploded(!exploded)}>Tách lớp</button></div>
 <aside className="advanced-panel" aria-label="Thiết kế giá đỡ điện thoại">
  <div className="advanced-meta"><span>THIẾT KẾ NGUYÊN MẪU</span><span>0{step+1} / 05</span></div>
  <h2>{stages[step].title}</h2><p className="mount-parts">{stages[step].parts}</p><div className="mount-stock-parts" aria-label="Mã linh kiện trong bước này">{mountInventory(step).map(p=><div key={p.code}><code>{p.code}</code><span>{p.name}</span><span>×{p.quantity}</span></div>)}</div><p>{stages[step].body}</p>
  <nav className="mount-stages" aria-label="Các bước lắp giá đỡ">{stages.map((s,i)=><button key={s.title} aria-current={i===step?'step':undefined} onClick={()=>onStep(i)}><span>0{i+1}</span>{s.title}</button>)}</nav>
  <div className="mount-nav"><button disabled={step===0} onClick={()=>onStep(step-1)} aria-label="Bước giá đỡ trước"><ChevronLeft size={17}/></button><span>{step===4?'Hoàn chỉnh':'Lắp lần lượt từng lớp'}</span><button disabled={step===4} onClick={()=>onStep(step+1)} aria-label="Bước giá đỡ tiếp"><ChevronRight size={17}/></button></div>
  <details><summary>Kích thước & linh kiện</summary><dl><div><dt>Thân máy tham chiếu</dt><dd>156,2 × 75,04 × 8,55 mm</dd></div><div><dt>Khối lượng máy</dt><dd>178 g · chưa gồm ốp</dd></div><div><dt>Khay dự kiến</dt><dd>23 stud · 184 mm</dd></div><div><dt>Khoảng giữa hai trụ cạnh</dt><dd>22 stud · cần căn theo máy và đệm</dd></div></dl><div className="mount-stock-parts">{mountInventory().map(p=><div key={p.code}><code>{p.code}</code><span>{p.name}</span><span>×{p.quantity}</span></div>)}</div><p>Số lượng trên lấy trực tiếp từ mô hình giá đỡ. Tất cả mảnh LEGO dùng hình học LDraw gốc, cùng thư viện với chiếc xe; không tạo khuôn mới hay kéo giãn mảnh. Viewer đặt cụm neo theo geometry chassis thật của model; số pin và hole-fit cuối cùng vẫn cần xác nhận trên xe đã độ.</p><p>Đây là linh kiện bổ sung, không giả định bộ 42096 còn dư đủ số lượng. Đệm và dây giữ điện thoại là phụ kiện riêng. <a href="/ldraw-part-credits.txt" target="_blank" rel="noreferrer">Nguồn asset & tác giả ↗</a></p><p>Đo lại máy, ốp và camera bump trước khi lắp. Các nguồn công bố kích thước hơi khác nhau. <a href="https://www.devicespecifications.com/en/model/ac6c5490" target="_blank" rel="noreferrer">Thông số Aris ↗</a></p></details>
  <details><summary>Kiểm tra trước khi chạy</summary><p>Đo khe mui, hành trình hệ treo và độ rơ của pin. Giữ camera thấp nhất có thể mà vẫn nhìn qua mui; kiểm tra rung, trượt máy và nguy cơ lật khi rẽ. Nếu bốn chân không đi được xuống các beam/frame mà viewer chọn, dịch cả cụm neo theo đúng lưới lỗ Technic trước khi lắp — không ép panel để vừa bản vẽ.</p></details>
  <details><summary>Lộ trình VLA</summary><p>Bắt đầu bằng MobileNetV3 + GRU học từ video lái xe của chính bạn. Khi cần hiểu “rẽ trái ở giao lộ” hoặc “đến vật màu đỏ”, fine-tune SmolVLA 450M trên dữ liệu xe. Điện thoại thu hình; máy tính chạy policy và gửi lệnh qua bộ giám sát.</p><a className="roadmap-link" href="/VLA-roadmap.md" target="_blank" rel="noreferrer">Đọc kế hoạch dữ liệu, training & triển khai <ArrowUpRight size={16}/></a></details>
 </aside>
 <div className="advanced-footnote">Linh kiện LDraw thật · neo theo chassis của model · pin-fit cần xác nhận trên xe thật</div>
 </>}
