'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {Check,ChevronDown,ChevronLeft,ChevronRight,Focus,Info,Layers,Maximize2,Pause,Play,RotateCcw,Scan,X} from 'lucide-react';
import {Slider} from '@/components/ui/slider';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Popover,PopoverContent,PopoverTrigger} from '@/components/ui/popover';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tooltip,TooltipContent,TooltipProvider,TooltipTrigger} from '@/components/ui/tooltip';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import Scene,{type SceneHandle} from './scene';
import type {ModelData,ViewerMode} from './model-types';

function IconButton({label,children,onClick,disabled=false,active=false}:{label:string;children:React.ReactNode;onClick:()=>void;disabled?:boolean;active?:boolean}){return <Tooltip><TooltipTrigger asChild><button type="button" className={`icon-button ${active?'is-active':''}`} aria-label={label} disabled={disabled} onClick={onClick}>{children}</button></TooltipTrigger><TooltipContent side="bottom">{label}</TooltipContent></Tooltip>}
const partName=(name:string)=>name.replace(/^42096 - /,'').replace(/\.(dat|ldr)$/,'');

export default function Home(){
 const [data,setData]=useState<ModelData|null>(null),[mode,setMode]=useState<ViewerMode>('explore'),[step,setStep]=useState(1),[explode,setExplode]=useState(0),[group,setGroup]=useState('all'),[selected,setSelected]=useState<number|null>(null),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState('1'),[replay,setReplay]=useState(0),[followStep,setFollowStep]=useState(true),[info,setInfo]=useState(false),[groupsOpen,setGroupsOpen]=useState(false);
 const scene=useRef<SceneHandle>(null),previewHost=useRef<HTMLDivElement>(null),main=useRef<HTMLElement>(null);
 const onReady=useCallback((d:ModelData)=>setData(d),[]);
 const maximum=data?.phaseCount??216;
 const changeStep=useCallback((n:number)=>{setStep(Math.max(1,Math.min(maximum,n)));setSelected(null);setGroup('all')},[maximum]);
 const currentStep=data?.steps[step-1],part=selected!==null?data?.parts[selected]:null,geometry=part?data?.geometries[part.geo]:null;
 const groupLabel=data?.groups.find(g=>g.id===group)?.label??'Toàn bộ xe';
 const items=useMemo(()=>{if(!data||!currentStep)return [];const counts=new Map<number,number>();currentStep.parts.forEach(id=>{const p=data.parts[id];counts.set(p.geo,(counts.get(p.geo)??0)+1)});return [...counts].map(([geo,quantity])=>({geo,quantity,info:data.geometries[geo]}))},[data,currentStep]);
 const visibleCount=data?.parts.filter(p=>(group==='all'||p.group===group)&&(mode==='explore'||p.step<=step)).length??0;
 const play=useCallback(()=>{if(!playing&&step===maximum)changeStep(1);setPlaying(p=>!p)},[playing,step,maximum,changeStep]);
 useEffect(()=>{if(!playing||mode!=='build')return;const timer=setInterval(()=>{setStep(s=>{if(s>=maximum){setPlaying(false);return s}return s+1});setSelected(null)},2600/Number(speed));return()=>clearInterval(timer)},[playing,mode,maximum,speed]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{const el=e.target as HTMLElement;if(el.closest('input,button,[role=slider],[role=combobox],[role=dialog]'))return;if(e.key==='Escape'){setSelected(null);setGroupsOpen(false)}if(mode!=='build')return;if(e.key==='ArrowRight'){e.preventDefault();setPlaying(false);changeStep(step+1)}if(e.key==='ArrowLeft'){e.preventDefault();setPlaying(false);changeStep(step-1)}if(e.code==='Space'){e.preventDefault();play()}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[mode,step,changeStep,play]);
 const selectMode=(value:string)=>{setMode(value as ViewerMode);setSelected(null);setGroup('all');setPlaying(false);setExplode(0)};
 const reset=()=>{setExplode(0);setGroup('all');setSelected(null);scene.current?.view('iso')};
 const selectPart=useCallback((id:number|null)=>{setSelected(id);setPlaying(false)},[]);
 return <TooltipProvider delayDuration={300}><Tabs value={mode} onValueChange={selectMode}><main className="workbench" ref={main}>
  <Scene ref={scene} step={step} explode={explode} group={group} selected={selected} mode={mode} replay={replay} followStep={followStep} onReady={onReady} onSelect={selectPart} previewHost={previewHost}/>
  <header className="topbar">
   <div className="identity"><span className="product-name">Porsche 911 RSR</span><span className="set-number">Technic / 42096</span></div>
   <TabsList className="mode-switch" aria-label="Chế độ xem"><TabsTrigger value="explore">Khám phá</TabsTrigger><TabsTrigger value="build">Lắp ráp</TabsTrigger></TabsList>
   <div className="header-actions"><IconButton label="Khôi phục góc nhìn" onClick={reset}><RotateCcw/></IconButton><IconButton label="Thông tin mô hình" onClick={()=>setInfo(true)}><Info/></IconButton></div>
  </header>
  <div className="scene-tools">
   <Popover open={groupsOpen} onOpenChange={setGroupsOpen}><PopoverTrigger asChild><button className="group-picker" disabled={!data}><Layers size={15}/><span>{groupLabel}</span><ChevronDown size={14}/></button></PopoverTrigger><PopoverContent className="groups-popover" align="start"><div className="popover-label">Cụm chi tiết</div><button className={group==='all'?'chosen':''} onClick={()=>{setGroup('all');setSelected(null);setGroupsOpen(false)}}><span>Toàn bộ xe</span>{group==='all'?<Check size={15}/>:<span>{data?.partCount}</span>}</button>{data?.groups.map(g=><button key={g.id} className={group===g.id?'chosen':''} onClick={()=>{setGroup(g.id);setSelected(null);setGroupsOpen(false)}}><span>{g.label}</span>{group===g.id?<Check size={15}/>:<span>{g.count}</span>}</button>)}</PopoverContent></Popover>
   <span className="visible-count">{data?visibleCount.toLocaleString('vi-VN'):'—'} chi tiết</span>
  </div>
  <div className="view-tools"><IconButton label="Vừa khung hình" onClick={()=>scene.current?.fit()}><Maximize2/></IconButton><IconButton label="Nhìn từ trên" disabled={mode==='explore'&&explode>.92} onClick={()=>scene.current?.view('top')}><Layers/></IconButton><IconButton label="Góc nhìn 3D" onClick={()=>scene.current?.view('iso')}><Scan/></IconButton></div>
  {(mode==='build'||part)&&<aside className={`guide ${mode==='build'?'build-guide':'part-guide'}`} aria-label={mode==='build'?'Hướng dẫn lắp ráp 3D':'Chi tiết đã chọn'}>
   <div className="guide-heading"><div><div className="small-label">{mode==='build'?`Bước ${String(step).padStart(3,'0')}`:'Chi tiết đã chọn'}</div><h2>{mode==='build'?(data?.groups.find(g=>g.id===currentStep?.group)?.label??'Lắp ráp'):geometry?partName(geometry.name):''}</h2></div>{part&&<IconButton label="Bỏ chọn mảnh" onClick={()=>setSelected(null)}><X/></IconButton>}</div>
   <div className="parts-preview" ref={previewHost}/>
   {mode==='build'?<><div className="parts-caption"><span>Mảnh cần dùng</span><span>{currentStep?.parts.length??0} mảnh</span></div><div className="parts-list">{items.map(item=><button key={item.geo} className="part-row" title={item.info.description} onClick={()=>{const id=currentStep?.parts.find(id=>data!.parts[id].geo===item.geo);if(id!==undefined){setSelected(id);setPlaying(false)}}}><span className="swatch" style={{background:item.info.colorHex}}/><span>{partName(item.info.name)}</span><span>×{item.quantity}</span></button>)}</div><div className="guide-actions"><button className="text-button" onClick={()=>{setPlaying(false);setReplay(r=>r+1)}}><RotateCcw size={14}/> Phát lại bước này</button><IconButton label="Camera tự theo bước" active={followStep} onClick={()=>setFollowStep(s=>!s)}><Focus/></IconButton></div><div className="guide-hint"><span className="new-piece-dot"/> Mảnh mới được tô màu cam</div></>:<><p className="part-description">{geometry?.description}</p><div className="part-facts"><span>{data?.groups.find(g=>g.id===part?.group)?.label}</span><span>Bước {part?.step}</span></div></>}
   {part&&<div className="selection-actions"><span className="selected-part"><span className="selection-dot"/>{geometry?partName(geometry.name):''}</span><button className="text-button" onClick={()=>scene.current?.focus()}><Focus size={14}/> Xem gần</button></div>}
  </aside>}
  <div className={`bottom-area ${mode==='build'?'build-bottom':''}`}>
   {mode==='explore'?<div className="explosion-control"><div className="control-caption"><span>Tách chi tiết</span><span>{Math.round(explode*100)}%</span></div><Slider aria-label="Tách từ xe hoàn chỉnh đến trải toàn bộ mảnh" min={0} max={1} step={.005} value={[explode]} disabled={!data} onValueChange={v=>{setExplode(v[0]);setSelected(null)}}/><div className="explosion-stops"><button className={explode===0?'active':''} onClick={()=>setExplode(0)}>Hoàn chỉnh</button><button className={Math.abs(explode-.4)<.01?'active':''} onClick={()=>setExplode(.4)}>Tách cụm</button><button className={explode===1?'active':''} onClick={()=>setExplode(1)}>Toàn bộ mảnh</button></div></div>:<div className="build-control"><div className="build-toolbar"><div className="step-navigation"><IconButton label="Bước trước" disabled={step<=1||!data} onClick={()=>{setPlaying(false);changeStep(step-1)}}><ChevronLeft/></IconButton><button className="play-button" aria-label={playing?'Tạm dừng':'Phát lắp ráp'} disabled={!data} onClick={play}>{playing?<Pause size={17}/>:<Play size={17} fill="currentColor"/>}</button><IconButton label="Bước tiếp" disabled={step>=maximum||!data} onClick={()=>{setPlaying(false);changeStep(step+1)}}><ChevronRight/></IconButton></div><label className="step-entry"><span>Bước</span><input type="number" min={1} max={maximum} value={step} aria-label="Đến bước lắp ráp" onChange={e=>{const n=Number(e.target.value);if(Number.isInteger(n)&&n>=1&&n<=maximum){setPlaying(false);changeStep(n)}}}/><span>/ {maximum}</span></label><Select value={speed} onValueChange={setSpeed}><SelectTrigger className="speed-select" aria-label="Tốc độ lắp"><SelectValue/></SelectTrigger><SelectContent>{['0.5','1','1.5','2'].map(s=><SelectItem key={s} value={s}>{s}×</SelectItem>)}</SelectContent></Select></div><Slider min={1} max={maximum} step={1} value={[step]} disabled={!data} aria-label="Tiến độ lắp ráp 3D" onValueChange={v=>{setPlaying(false);changeStep(v[0])}}/></div>}
   <p className="interaction-hint">{mode==='explore'&&explode>.92?'Kéo để di chuyển · Cuộn để zoom · Chạm để chọn mảnh':'Kéo để xoay · Cuộn để zoom · Chạm để chọn mảnh'}</p>
  </div>
  <Dialog open={info} onOpenChange={setInfo}><DialogContent className="info-dialog"><DialogTitle>Porsche 911 RSR</DialogTitle><DialogDescription>LEGO Technic 42096 · 2019</DialogDescription><div className="info-copy"><p>Khám phá mô hình, tách từng cụm hoặc trải riêng toàn bộ chi tiết. Chế độ Lắp ráp hướng dẫn trực tiếp trong không gian 3D.</p><p>Trình tự gồm {maximum} bước theo mô hình LDraw của Philippe Hurbain. Đây không phải ánh xạ từng bước của sách LEGO. Chuyển động đưa mảnh vào được dựng để minh họa, chưa phải mô phỏng va chạm cơ khí.</p><p>Mô hình có 1.586 phần tử 3D; bộ LEGO có 1.580 mảnh. Một số sticker chưa có trong mô hình.</p><p><a href="https://forums.ldraw.org/thread-23139.html" target="_blank" rel="noreferrer">Mô hình gốc</a><a href="https://github.com/ashemag/human-atlas" target="_blank" rel="noreferrer">Human Atlas</a><a href="/ATTRIBUTION.txt" target="_blank" rel="noreferrer">Nguồn & giấy phép</a></p></div></DialogContent></Dialog>
 </main></Tabs></TooltipProvider>;
}
